resolver 127.0.0.11 valid=10s ipv6=off;

upstream api_rest {
    server voce-aluga-api-rest:8081;
}

upstream api_web {
    server voce-aluga-api-web:8082;
}

server {
    listen 8080;
    server_name _;

    client_max_body_size 20m;

    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    location /api/ {
        set $api_rest_upstream http://voce-aluga-api-rest:8081;
        proxy_pass $api_rest_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /actuator/ {
        set $api_rest_upstream http://voce-aluga-api-rest:8081;
        proxy_pass $api_rest_upstream;
        proxy_set_header Host $host;
    }

    location / {
        set $api_web_upstream http://voce-aluga-api-web:8082;
        proxy_pass $api_web_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
