upstream api_rest {
    server voce-aluga-api-rest:8081;
}

upstream api_web {
    server voce-aluga-api-web:8082;
}

server {
    listen 8080;
    server_name _;

    client_max_body_size 20m;

    location /api/ {
        proxy_pass http://api_rest;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /actuator/ {
        proxy_pass http://api_rest;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://api_web;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
