apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-primary-init
  namespace: voce-aluga
data:
  01-replication-user.sql: |
    CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED WITH mysql_native_password BY 'replpass';
    ALTER USER 'repl'@'%' IDENTIFIED WITH mysql_native_password BY 'replpass';
    GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
    FLUSH PRIVILEGES;
