apiVersion: v1
kind: Secret
metadata:
  name: voce-aluga-db
  namespace: voce-aluga
type: Opaque
stringData:
  url: jdbc:mysql://mysql-primary:3306/db_voce_aluga
  username: root
  password: senha123
