spring.application.name=voce-aluga-web

server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_voce_aluga}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:senha123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

vocealuga.api.base-url=${API_REST_URL:http://localhost:8081}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
