spring.application.name=voce-aluga


spring.datasource.url=jdbc:mysql://localhost:3306/db_voce_aluga
spring.datasource.username=vocealuga
spring.datasource.password=senha123

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto= create # ou update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server port
server.port=8080

